### ISSUE TITLE
Typo in recovery_common.py

### ISSUE THREAD

**Issue by iktyrrell** [dell/dell-recovery#75]
Attempting to build a custom image for bionic, I encountered the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/Dell/recovery_backend.py", line 456, in assemble_image
    white_tree("copy", white_pattern, base_mnt, assembly_tmp)
  File "/usr/lib/python3/dist-packages/Dell/recovery_common.py", line 91, in white_tree
    return _tree(action, whitelist, src, dst, base, True)
  File "/usr/lib/python3/dist-packages/Dell/recovery_common.py", line 120, in _tree
    _tree(action, list, src_name, dst_name, base, white))
  File "/usr/lib/python3/dist-packages/Dell/recovery_common.py", line 132, in _tree
    shtuil.copy(src_name, dst_name)
NameError: name 'shtuil' is not defined
```
There is a typo `shtuil` should be `shutil` - fixing this in the file alleviated the error.

**Comment by superm1** [comment]
Can you submit a pr for this? Obviously that's correct.

**Comment by luislobo** [comment]
This should be closed
