### ISSUE TITLE
DBus error when more than 2 dell-bto-autobuilder run together on the same host

### ISSUE THREAD

**Issue by jason-lo** [dell/dell-recovery#78]
When there are more than 2 dell-bto-autobuilder execute at the same time on the same host. Only first one can successfully completed. The following ones would encounter following error.

------------------------------------------------------
13:30:54 Done
13:30:54 
13:30:54 Generating BTO - executing /usr/share/dell/bin/dell-bto-autobuilder...
13:30:54 
13:30:54 
13:31:20 ERROR:dbus.proxies:Introspect error on :1.3021:/RecoveryMedia: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
13:32:10 Received org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken. when closing recovery-media-backend DBus service
13:32:10 Traceback (most recent call last):
13:32:10   File "/usr/share/dell/bin/dell-bto-autobuilder", line 319, in <module>
13:32:10     iface.request_exit() # will call atexit in dell backend
13:32:10   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
13:32:10     **keywords)
13:32:10   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
13:32:10     message, timeout)
13:32:10 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by superm1** [comment]
Yes I think this is currently a limitation.  If there is a need for this; can you run it in a container instead perhaps?

**Comment by jason-lo** [comment]
Yes, now we run it inside Vagrant (base on VirtualBox). It turns out Vagrant has its known issue on disconnecting randomly during the build. If we can break through this limitation, we can have more efficiency on building ISO's on bare metal.

**Comment by superm1** [comment]
I would think you're better off using lxc or docker in this instance.  Containers are much more efficient use of resources for this type of thing.

**Comment by jason-lo** [comment]
We use Vagrant for a reason that during the build we need to mount ISO for processing. For LxC or Docker we need to break through privileges that makes no much sense for what the application layer containers, such as Docker, are designed to be.
